// <auto-generated />
using IS413_Project1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IS413_Project1.Migrations
{
    [DbContext(typeof(TourDbContext))]
    [Migration("20210317205055_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13");

            modelBuilder.Entity("IS413_Project1.Models.TourGroup", b =>
                {
                    b.Property<int>("TourGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TourSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TourTime")
                        .HasColumnType("TEXT");

                    b.HasKey("TourGroupId");

                    b.ToTable("Group");
                });
#pragma warning restore 612, 618
        }
    }
}
